project:
  type: website
  output-dir: _site

website:
  title: "Faadil Mustun"
  favicon: dolphin_icon.png
  navbar:
    background: primary
    right:
      - text: About
        href: index.qmd#about
      - text: News
        href: index.qmd#news
      - text: Publications
        href: index.qmd#publications
      - text: Talks
        href: index.qmd#selected-talks-posters
      - text: Education
        href: index.qmd#education

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    grid:
      body-width: 1050px
      margin-width: 80px
